on:
  push:
    branches: 
      - k3c

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: init
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
      - name: build
        run: |
          git clone https://github.com/paldier/K3C.git
          cd K3C
          sed -i 's/git clone 2>&1 | grep -- --recursive/git version/' include/prereq-build.mk
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          wget https://raw.githubusercontent.com/felix-fly/openwrt-build/master/k3c.config -O .config
          wget https://raw.githubusercontent.com/felix-fly/openwrt-build/master/patches/001-glib-gdate-suppress-string-format-literal-warning.patch -P tools/pkg-config/patches
          wget https://raw.githubusercontent.com/felix-fly/openwrt-build/master/patches/210-openssl-1.1.x-compat.patch -P tools/mkimage/patches
          make -j$(nproc) V=s
          cd ..
          mkdir bin
          mv K3C/bin/* bin
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: bin
